### PR TITLE
Test with Rails 6, drop Rails 4.2 support, remove deprecation warnings for Rails 6.1

### LINKED ISSUE #43: Deprecation Warnings for Rails 6.1
DEPRECATION WARNING: NOT conditions will no longer behave as NOR in Rails 6.1. To continue using NOR conditions, NOT each conditions manually (`.where.not(:archived_at => ...).where.not(:archive_number => ...)`)

### PR DESCRIPTION
**Pull request by aried3r**
This is based on #40, so it'll just sit around until that is merged and if you're ok with this PR (I will rebase after #40 is done so there's no duplication).

I just opened this to see if it works on Travis.

Fixes #43.

### CODE REVIEW

**Comment by aried3r** [comment]
Updated to the RC2 which came out yesterday, seems everything still works :)

**Comment by aried3r** [comment]
I dropped Rails 4.2 support because it's been EOL for a while now and I believe the benefit of supporting Rails 6 outweighs [fixing the CI](https://travis-ci.org/github/expectedbehavior/acts_as_archival/builds/667715434) for Rails 4.2.

Friendly ping @janxious.

**Comment by aried3r** [comment]
The Travis CI status doesn't seem to update for me on GitHub, but [here's the successful test run](https://travis-ci.org/github/expectedbehavior/acts_as_archival/builds/667718830?utm_medium=notification&utm_source=github_status).

**Comment by aidandamerell** [comment]
Nice work! I was about to raise a PR to fix the deprecation warnings, this looks to solve it. Any insight on when this will get merged and released?

**Comment by janxious** [comment]
I'll try to take a peak at this today.

**Comment by aried3r** [comment]
@janxious, have you had time to review this? :)

If you think this looks okay, I'd send a follow-up PR soon which would remove the deprecated methods so we can release a new major version with breaking changes (Rails 4.2, removed deprecated methods). WDYT?

**Comment by janxious** [comment]
@aried3r Changes look good. Just getting environment stuff done so I can run tests and whatnot.

**Comment by janxious** [comment]
So things I ran into: lingering rails 4.2 gem lock file, rubocop is locked to ruby EOL'ed 2.4 and needs to be updated to understand new ruby so local rake will work. There are a number of issues reported by rubocop that should be inspected/ignored, but they're not necessarily related to this work here.

The tests do in fact pass in appraisal, which is good. :D

**Comment by aried3r** [comment]
>  lingering rails 4.2 gem lock file

I believe this is local only. `.lock` files are being ignored. 

https://github.com/expectedbehavior/acts_as_archival/blob/e51b1833a73e9100fe93fbf4ecc02eadea9776f8/.gitignore#L7

However we _could_ add a `Gemfile.lock` at the root of the repository as [bundler recommends](https://bundler.io/blog/2018/01/17/making-gem-development-a-little-better.html) (in the past, the opposite was recommended).

> rubocop is locked to ruby EOL'ed 2.4 and needs to be updated to understand new ruby so local rake will work.

I worked on this in #42, but I'll have to revisit that branch, preferably after this branch has been merged since it contains some updates already.

Is there anything you'd like me to do in this branch before we start work on removing deprecations, updating rubocop etc?

**Comment by janxious** [comment]
> I believe this is local only. .lock files are being ignored.
Yup, you're right. I deleted it and didn't pay attention to my git status.

> However we could add a Gemfile.lock at the root of the repository
I'm pretty pro that. I think we started that way and backed off after some code review in the long distant past. :D

> Is there anything you'd like me to do in this branch before…
If you are okay with merging without release and doing a removal of 2.4 in the next branch or a related one, then nope.

**Comment by aried3r** [comment]
> I'm pretty pro that. I think we started that way and backed off after some code review in the long distant past. :D

Nice, I'll get to it in the next PR.

> If you are okay with merging without release and doing a removal of 2.4 in the next branch or a related one, then nope.

I'm okay with that. 

Are you sure you want to drop Ruby 2.4 support? I'm all for dropping old Ruby versions, but rubygems has since released [stats](https://stats.rubygems.org/) and there's a lot of people still on 2.3. Should we maybe try to add 2.3 support again? I don't think there's anything in 2.4 that this gem uses that would prevent it and it _could_ be as simple as adding it back to `.travis.yml`. WDYT?

Incidentally the two of us decided to drop support for it [last year](https://github.com/expectedbehavior/acts_as_archival/pull/40#issuecomment-511415666).

**Comment by janxious** [comment]
> Are you sure you want to drop Ruby 2.4 support? I'm all for dropping old Ruby versions, but rubygems has since released stats and there's a lot of people still on 2.3. Should we maybe try to add 2.3 support again?

It would be nice, but the shims for old versions of rails and ruby make it harder to maintain this project long-term because the details are always really… specific.

Unrelated, and it's my fault, but I think the Changelog should be updated to reflect ruby version support drops in addition to rails, though I think rails versions are largely driving those drops. (specifically https://github.com/expectedbehavior/acts_as_archival/blob/master/CHANGELOG.md#140---july-10-2019)

As long as the old versions are around I don't have any problem with cutting old ruby and rails.

If you're very invested in ruby 2.3 support then I won't turn it away just because it's EOL, but I might turn it away if the resulting gem code is funky enough 😸

**Comment by aried3r** [comment]
Alright, I'll have a stab at it once this PR is done. Anything more you'd like to see in this one?

**Comment by janxious** [comment]
Nope, merged!

**Pull request merged**
