### PR TITLE
Fix Travis

### PR DESCRIPTION
**Pull request by aried3r**
At the end of this PR hopefully the builds will be green again :)

### CODE REVIEW

**Comment by aried3r** [comment]
@janxious I believe you have to reactivate this projects on Travis CI so PRs get a status from it. If I remember correctly they changed something in the past which made projects that were inactive for some time kind of paused.
Can you maybe check? It would be nice to see if PRs work on GitHub directly.

https://docs.travis-ci.com/user/migrate/open-source-repository-migration#what-will-happen-to-my-travis-ciorg-repository

**Comment by aried3r** [comment]
It's all green now :)

**Comment by janxious** [comment]
I'm not going to be sad if you want to remove 2.1, 2.2, and 2.3 ruby, since they are all EOL.

**Comment by aried3r** [comment]
I thought you'd never ask 🤩 I'll get on it tomorrow.

On that note, are there any considerations regarding dropping Rails versions? Given that 6.0 should be released soon?

**Comment by janxious** [comment]
I recently removed 4.1 in another PR because it was EOL. We will do the same for 4.2 once 6 is out (as that will EOL 4.2), and do our normal thing for old versions where we keep a branch around for anyone who needs it for whatever reason.

**Comment by janxious** [comment]
And I guess to go further, we will only do that once we have actual 6.0 support, since I haven't been following what ARec changes there are. There is almost always some reworking that needs to be done with new major and minor versions.

**Comment by aried3r** [comment]
Sounds like a good plan!
Btw, since there's been a few deprecated methods for a long time now, how do you feel about a new release where these are removed? Maybe a 2.0?

**Comment by janxious** [comment]
> how do you feel about a new release where these are removed?

Seems reasonable. I almost did it last time I was in here but knew 4x compatibility was gone soon and decided to hold off.

**Comment by aried3r** [comment]
Ok, that's fair. Maybe the removal of deprecations should indeed go along with the removal of Rails 4.2 support so not every release contains breaking changes.

That being said, I see this PR as done unless you have some more remarks? :)

**Comment by janxious** [comment]
have any thoughts on using the ruby version in gemspec to make script/setup install a valid ruby version for setting the project up?

**Comment by aried3r** [comment]
I'm not quite sure what you mean, could you elaborate?

**Comment by janxious** [comment]
There is currently not a .ruby-version set for the project, which makes sense for appraisal, but you can also run the test suite with whatever the default is. Right now we are depending on 2.4x+ in the gemspec, so making the `script/setup` script use that to install/use a valid ruby as part of setup would be nice. I just haven't ever seen anything that interacts .ruby-version and .gemspec files.

**Comment by aried3r** [comment]
Isn't it enough that bundler will fail when using an unsupported Ruby version? That way we leave this task up to bundler and can leave out complexity in the setup script.

```console
$ rbenv install 2.3.8
$ rbenv local 2.3.8
$ script/setup

---=== Bundling ===---
Fetching gem metadata from https://rubygems.org/.........
acts_as_archival-1.4.0 requires ruby version >= 2.4, which is incompatible with the current version,
ruby 2.3.8p459
```

**Comment by janxious** [comment]
Does bundler install rubys now?

The intent of `script/setup` is to automatically take you from nothing to working env.

**Comment by aried3r** [comment]
I strongly believe this is outside the scope of `script/setup` as it's not what it's doing right now. My example was actually wrong, this is what happens if you *just* install Ruby.

```console
$ rbenv install 2.3.8
$ rbenv local 2.3.8
$ script/setup

---=== Bundling ===---
rbenv: bundle: command not found
```

`script/setup` assumes Ruby is installed (a good assumption, but definitely not "nothing". On macOS Ruby, Python etc will soon not be included anymore, they are deprecated as of Catalina, see [the release notes of the beta](https://developer.apple.com/documentation/macos_release_notes/macos_catalina_10_15_beta_4_release_notes). So we'd have to install Ruby, install bundler if it's Ruby <2.6 since only 2.6 includes [bundler as a default gem](https://www.ruby-lang.org/en/news/2018/12/25/ruby-2-6-0-released/), then install the gems.)

So I think we should define what "nothing" means, which in my case would actually mean _"you have Ruby installed and will follow the errors displayed when not all dependencies are met"_, definitely a bit more than nothing, but some assumptions can be made, given that this is a Ruby gem,. :)

Rails for example does indeed assume you have Ruby installed, since their setup script is written in Ruby itself. But they do [install bundler](https://github.com/rails/rails/blob/6-0-stable/railties/lib/rails/generators/rails/app/templates/bin/setup.tt#L16) for you if you don't have it.

So what do you think about just adding `gem bundle install --conservative` to the setup script and leaving the rest (checking the Ruby version) to bundler and rubygems?

**Comment by janxious** [comment]
My general assumption of "nothing" is "homebrew is installed" or "apt is available". :)

That said, I am okay with it in its current state, or with the addition of gem installation you proposed. I was just curious if you knew anything about automating ruby installation via gemspecs that doesn't involve grep-like actions.

**Comment by aried3r** [comment]
Ah, then we're on the same page and I just misunderstood. :)

Would it be ok if I add the `gem install bundler` in a different PR? And I'm not completely convinced we should add that, but I assume people will come and open an issue if there's a problem with that.

Then this PR can stay focused on Travis and the related cleanup.

**Comment by janxious** [comment]
We can just not do the gem thing for now. We get little enough traffic on this from potential contributors that actually need to run script/setup that I think it's easy to explain for anyone who runs into problems.

**Pull request merged**
