### PR TITLE
Appraisals for Rails 5.0-stable

### PR DESCRIPTION
**Pull request by aried3r**

### CODE REVIEW

**Comment by janxious** [comment]
Could I talk you into removing the 5.1 beta? Happy to add 5.1 in once it's released.

**Comment by aried3r** [comment]
Done! I thought you might want the beta because Rails 5.0 was also included as a beta version.

Anyway, I've removed it and pushed the changes.

**Comment by janxious** [comment]
Yeah, that was a bad timing situation. We weren't sure if it would work with rails 5 at all, and never circled back to fix it to be non-beta. :)

**Comment by aried3r** [comment]
> We weren't sure if it would work with rails 5 at all

On that note I'd like to ask if you'd have the time to look into #27 or guide me towards a solution? I'd love to have the tests running on Travis CI. No worries if it's not a priority for you. :)

**Pull request merged**
