### PR TITLE
Fix minor error in documenation

### PR DESCRIPTION
**Pull request by armilam**
An example for `r.archived?` incorrectly listed the output of `r.archive_number`. I changed that to the correct boolean value.

### CODE REVIEW

**Comment by janxious** [comment]
The documentation was correct before. `#archived?` purposefully returns the archive number.

I would not be opposed to a discussion/PR that changes that, but this leans on ruby truthiness to do its work. I can a situation in which that would be surprising if you were using it to do serialize the method output for something instead of just using it as a check in code.

[relevant truthiness test](https://github.com/expectedbehavior/acts_as_archival/blob/05dc4e5d6f621dcc76028d88699e0e7a178ff78c/test/basic_test.rb#L7)

**Comment by armilam** [comment]
Ah, my mistake. I was reading through the documentation and that struck me as strange and I made an assumption without testing it - sorry about that.

As for changing the actual functionality, I haven't yet run into a situation where that matters, however I imagine I will soon when I add archived state to some API GET requests.

I have to imagine you guys thought this through and have a good reason to return the `archive_number` when calling `#archived?`.

**Comment by armilam** [comment]
I'm happy to close this and delete the branch if no discussion happens here.

**Comment by janxious** [comment]
"purposefully" above may have been too strong. There was a good reason, probably, but I no longer remember it.

My suspicion is it was straightforward at the time it was coded and we hadn't run into any situations where we needed it do something different. I'm totally down to change the behavior. It will be a major version change since that is an API breaker, but it's probably good to not surprise users of the library.

**Comment by janxious** [comment]
To say that another way, having to `!!` a method ending in `?` is weird.

**Comment by armilam** [comment]
Agreed that a `?` method should always return `true` or `false`.

**Comment by janxious** [comment]
Opened #22 to deal with the code underlying this.

**Pull request closed without merging**
